# Generated by Django 3.0.7 on 2020-06-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address_2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
