# Generated by Django 3.0.7 on 2020-07-15 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20200715_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='location',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='post_code',
        ),
        migrations.CreateModel(
            name='ShopWebInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, max_length=100)),
                ('fb_page', models.URLField(blank=True, max_length=100)),
                ('instagram_page', models.URLField(blank=True, max_length=100)),
                ('trip_advisor_page', models.URLField(blank=True, max_length=100)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopAddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address_1', models.CharField(blank=True, max_length=100)),
                ('address_2', models.CharField(blank=True, max_length=100)),
                ('post_code', models.CharField(blank=True, max_length=100)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop')),
            ],
        ),
    ]
