# Generated by Django 3.0.7 on 2020-07-16 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20200715_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopaddressinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shopwebinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='shopaddressinfo',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shops.Shop'),
        ),
        migrations.AlterField(
            model_name='shopwebinfo',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shops.Shop'),
        ),
    ]
