# Generated by Django 3.0.7 on 2020-06-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='currency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
