# Generated by Django 3.0.7 on 2020-06-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20200616_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'UK Pound')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='menu',
            name='language',
            field=models.CharField(choices=[('GR', 'Greek'), ('EN', 'English'), ('DE', 'German'), ('SP', 'Spanish'), ('IT', 'Italian'), ('RS', 'Russian'), ('CH', 'Chinese')], default='GR', max_length=2),
        ),
    ]
