# Generated by Django 3.0.7 on 2020-07-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20200616_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
